# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 1454780720791cafddf1ef8119998b8c8f040da4d41ddaf08684705a968511a3248f2f59c3f34a28e1eda0e3b07c42a770dc413ac811e89b525053dd0ebcdbd1

test:
  secret_key_base: b42f0c9bfa874aeb6a237d79513fadc9a73faa8f86f1fa5fb128c1f6006fd7655997cb57664e62a08793b170973deb4f20ddad828f13aeae4030ada1da5bc00c

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
